Increment 5
frolmr/metrics pull request #5
Opened 2024-12-01 21:04 UTC by frolmr

2024-12-02 11:35 UTC, zhark0vv requested changes

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +import (
Лучше вынести логику хендлеров за пределы main-package, например, в controller.
Чем меньше и компактнее main, тем лучше.

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +type Metricable interface {
Супер, что ты делаешь интерфейсы по месту использования.
Единственное замечание - их стоит сделать приватными.

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +	// r.Use(middleware.ContentCharset("UTF-8"))
Старайся избегать незначимвых комментариев в коде.

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +type MemStorage struct {
Тут немного не понял решения.
Для чего структура storage сделана тут, если есть отдельный пакет для этого?

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +		CounterMetrics: make(map[string]int64),
Создание storage лучше инкапсулировать от потребителя, он не должен управлять структурой внешнего модуля. Рекомендую скрыть конкретные мапы за конструктором.

2024-12-02 11:35 UTC, zhark0vv commented on cmd/server/main.go
> +		panic(err)
log.Panic(err), так будет видно, что пошло не так.

2024-12-02 11:35 UTC, zhark0vv commented on internal/agent/config/config.go
> +		panic(err)
Стоит вернуть ошибку, а паниковать только на верхнем слое приложения. Так проще будет с дебагом, если понадобится.
Старайся паниковать и фаталить только на верхних слоях (исключение: must-методы, когда вероятность паники стремится к 0)

2024-12-02 11:35 UTC, zhark0vv commented on internal/agent/metrics/collector.go
> +func CollectMetrics(counterMetrics map[string]int64, gaugeMetrics map[string]float64) (map[string]int64, map[string]float64) {
Вместо публичного пакета, лучше сделать публичную структуру с методом, например, MetricCollector, и закрыть ее интерфейсным типом на месте использования.

2024-12-02 11:35 UTC, zhark0vv commented on internal/agent/metrics/reporter.go
> +	client := resty.New()
Опять же, если закрыть пакет за структурой, то клиента можно будет переиспользовать (а его стоит переиспользовать из-за особенностей HTTP/TLS).

2024-12-02 11:35 UTC, zhark0vv commented on internal/common/constants/constants.go
> +package constants
Это часть доменной логики, вместо пакета `common`, я бы предпочел видеть `domain`.

2024-12-02 11:35 UTC, zhark0vv commented on internal/common/utils/utils.go
> +package utils
Этому пакету самое место в pkg.
https://github.com/golang-standards/project-layout

2024-12-02 11:35 UTC, zhark0vv commented on internal/server/config/config.go
> +		panic(err)
Аналогично клиенту, лучше паниковать на самом верхнем уровне.

2024-12-02 11:35 UTC, zhark0vv commented on internal/server/handlers/handlers.go
> +func UpdateMetricHandler(repo storage.Repository) http.HandlerFunc {
Также лучше закрыть за структурой (и интерфейсом).

2024-12-02 11:35 UTC, zhark0vv commented on internal/server/handlers/handlers.go
> +		// Пришлось вернуть, т.к. в автотестах проверка обязательная, а middlware
Можешь пояснить детали этого комментария, пожалуйста? Не совсем понял.

2024-12-02 11:35 UTC, zhark0vv commented on internal/server/handlers/handlers_test.go
> +		// 	name:        "fail content-type request",
Незначащие комментарии.

2024-12-02 11:35 UTC, zhark0vv commented on internal/server/storage/repository.go
> +type Repository interface {
Интерфейсы лучше порождать по месту использования.
Рекомендую ознакомиться с: https://github.com/golang-standards/project-layout/tree/master/pkg

2024-12-02 18:42 UTC, frolmr commented on cmd/server/main.go
> +import (
вынес в router.go

2024-12-02 18:43 UTC, frolmr commented on cmd/server/main.go
> +type Metricable interface {
это мусорный код, который забыл убрать

2024-12-02 18:43 UTC, frolmr commented on cmd/server/main.go
> +	// r.Use(middleware.ContentCharset("UTF-8"))
почистил

2024-12-02 18:44 UTC, frolmr commented on cmd/server/main.go
> +type MemStorage struct {
это мусорный код остался от первых инкрементов, когда "накидывал" решение
убрал

2024-12-02 18:44 UTC, frolmr commented on cmd/server/main.go
> +		CounterMetrics: make(map[string]int64),
убрал в "конструктор"

2024-12-02 18:44 UTC, frolmr commented on cmd/server/main.go
> +		panic(err)
поправил

2024-12-02 18:45 UTC, frolmr commented on internal/agent/config/config.go
> +		panic(err)
поправил

2024-12-02 18:51 UTC, frolmr commented on internal/agent/metrics/collector.go
> +func CollectMetrics(counterMetrics map[string]int64, gaugeMetrics map[string]float64) (map[string]int64, map[string]float64) {
Не уверен, что до конца осознал твой комментарий, но в итоге сделал так:
- есть структура MetricsCollection
- эта структура реализует интерфесы Collector и Reporter
- вызываю там где надо методы структуры MetricsCollection для сбора и отправки метрик
Возможно, все-таки, не то)))

2024-12-02 18:52 UTC, frolmr commented on internal/agent/metrics/reporter.go
> +	client := resty.New()
тут валиден предыдущий комментарий

2024-12-02 18:52 UTC, frolmr commented on internal/common/constants/constants.go
> +package constants
убрал в domain.go

2024-12-02 18:52 UTC, frolmr commented on internal/common/utils/utils.go
> +package utils
унес в pkg

2024-12-02 18:52 UTC, frolmr commented on internal/server/config/config.go
> +		panic(err)
fixed

2024-12-02 18:53 UTC, frolmr commented on internal/server/handlers/handlers.go
> +func UpdateMetricHandler(repo storage.Repository) http.HandlerFunc {
тут аналогично не уверен, что полностью осознал best practice
посмотри, пожалуйста, все ли так поправил
P.S. делал по аналогии с учебными материалами

2024-12-02 18:56 UTC, frolmr commented on internal/server/handlers/handlers.go
> +		// Пришлось вернуть, т.к. в автотестах проверка обязательная, а middlware
не обращай внимания
показалось, что в 1-м инкременте нужно эксплицитно проверять этот заголовок
я его начал проверять, потом перенес в middlware chi, но начали падать автотесты, потому что в 1-м инкременте они отправляют заголовок, во втором не отправляют
в итоге просто это выпилили и все, оно ни на что не влияет принципиально

2024-12-02 18:56 UTC, frolmr commented on internal/server/handlers/handlers_test.go
> +		// 	name:        "fail content-type request",
удалил

2024-12-02 19:01 UTC, frolmr commented on internal/server/storage/repository.go
> +type Repository interface {
а вот тут я что-то гарантированно не до конца понял
что значит `по месту использования`?
т.е. если я в каком-то пакете использую в качестве параметра функции interface, то его там и объявлять? а что если таких пакетов несколько?
просто логика моя была такая: 
- есть методы, которые что-то должны сделать с репозиторием/хранилищем (добавить, удалить, получить и т.д.)
- эти методы могут быть в разных местах модуля
- сегодня у меня in-memory хранилка, завтра файловая, потом БД
- мне при этом не нужно менять реализацию методов, которые принимают параметром interface
- я меняю только в месте их вызов: передаю разные конкретные хранилища

2024-12-04 09:06 UTC, zhark0vv commented on cmd/agent/main.go
> +		os.Exit(1) // NOTE: не знаю на сколько это правильное/удачное решение
log.Fatal() делает это сам. Если нужно такое поведение можно использовать его.
Тут это вполне уместно.

2024-12-04 09:13 UTC, zhark0vv approved these changes

2024-12-04 09:13 UTC, zhark0vv commented on internal/agent/config/config.go
> +	} else {
Здесь можно без else, эти ветки взаимоисключающие.

2024-12-04 09:13 UTC, zhark0vv commented on internal/agent/config/config.go
> +	} else {
Здесь можно без else, эти ветки взаимоисключающие.

2024-12-04 09:13 UTC, zhark0vv commented on internal/agent/metrics/collector.go
> +	CollectMetrics() (map[string]int64, map[string]float64)
Это интерфейс по месту реализации. :)
Ты описал реализацию и тут же закрыл ее за интерфейсом.

Интерфейс по месту использования - это когда так:

```
package service

import (
	"fmt"
)

// Repository — приватный интерфейс
type repository interface {
	FindByID(id int) (string, error)
}

// repoImpl — конкретная реализация репозитория
type repoImpl struct {
	data map[int]string
}

func (r *repoImpl) FindByID(id int) (string, error) {
	if name, ok := r.data[id]; ok {
		return name, nil
	}
	return "", fmt.Errorf("record not found")
}

// Service — структура сервиса, использующего репозиторий
type Service struct {
	repo repository
}

// NewService — конструктор сервиса с внедрением зависимости
func NewService(repo repository) *Service {
	return &Service{repo: repo}
}

package main

import (
	"fmt"
)

// Repository — приватный интерфейс
type repository interface {
	FindByID(id int) (string, error)
}

// Service — структура сервиса, использующего репозиторий
type Service struct {
	repo repository
}

// NewService — конструктор сервиса с внедрением зависимости
func NewService(repo repository) *Service {
	return &Service{repo: repo}
}

// GetUserName — метод сервиса, использующий репозиторий
func (s *Service) GetUserName(id int) (string, error) {
	return s.repo.FindByID(id)
}
```

При этом, сама реализация репозитория находится в другом пакете.
Так ты увеличишь инкапсуляцию, соблюдаешь единую ответственность и используешь Go-way подход к расположению интерфейсов.

2024-12-06 16:02 UTC, zhark0vv commented on internal/server/storage/repository.go
> +type Repository interface {
Извини, я изначально положил неправильную ссылку.
[Тут](https://www.youtube.com/watch?v=eYHCCht8eX4&ab_channel=%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%A2%D1%83%D0%B7%D0%BE%D0%B2%E2%80%94Golang) классно рассказывают об этом.

2024-12-13 15:55 UTC, merged