Increment 9
frolmr/metrics pull request #9
Opened 2024-12-22 10:43 UTC by frolmr

2024-12-22 14:56 UTC, zhark0vv requested changes

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/gzipper/gzipper.go
> +// Close закрывает gzip.Writer и досылает все данные из буфера.
Давай переделаем на английский. Это, конечно, вкусовщина, но тон хороший. :)

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Рекомендую здесь избавиться от глобального состояния логгера.

Смотри, ты используешь Singleton, у тебя есть один глобальный логгер.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing

В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами.
Здесь стоит сделать просто обертку, ее конструктор, создать объект логгера в main-пакете и инжетировать ее туда, где она нужна.

Знаю, что так сделано в учебных материалах.
Пример дан для демонстрации. Обычно мы стараемся избегать глобальных зависимостей.

Рекомендую тебе разобраться детальнее с концепцией Dependency Injection и встроить логгер туда, где он нужен явно.

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/logger/logger.go
> +	// преобразуем текстовый уровень логирования в zap.AtomicLevel
Давай уберем лишние комментарии.

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/middleware/compressor.go
> +		// по умолчанию устанавливаем оригинальный http.ResponseWriter как тот,
И эти.

2024-12-22 14:56 UTC, zhark0vv commented on internal/agent/metrics/reporter.go
> +func (mc *MetricsCollection) ReportCounterMetrics(client *resty.Client) {
Не стоит делать клиент зависмостью (*resty.Client), инкапсулируй его внутрь `MetricsCollection`
Метод не должен зависеть от архитектуры.

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/config/config.go
> +	switch restoreString {
```
restore = false
if restoreString == "true"  {restore = true}
```

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/storage/snapshot.go
> +func (ms *MemStorage) SaveToSnapshot(filePath string) {
Концептуально в Go, лучше не принимать имя файла на вход, а вместо этого использовать дескрипторы из io.
Например, io.Writer, тогда твоему коду будет безразлично, куда ты пишешь результат.

Пусть решение о том, куда писать примет потребитель, а не Storage.

2024-12-22 14:56 UTC, zhark0vv commented on internal/server/storage/snapshot.go
> +	for name, value := range ms.CounterMetrics {
Можно перейти из пулл-модели (читаем весь репозиторий и кладем всю пачку рез в х минут) на пуш-модель. Пуш-модель - это когда сервисный слой создаст в очереди событие о том, что метрика создана, а читатель обработает и положит в файл.

```
func (st *MemStorage) AddMetric(metric Metric) {
	st.mu.Lock()
	st.metrics = append(st.metrics, metric)
	st.mu.Unlock()
	st.events <- metric // Пушим событие в канал
}

func (st *MemStorage) SaveToSnapshot(io.Writer) {
	go func() {
		for {
			select {
			case metric := <-st.events: // Обрабатываем новое событие из канала
				_, err = writer.Write([]byte(fmt.Sprintf("Metric: %s, Value: %d, Time: %s\n", 
					metric.Name, metric.Value, metric.Time)))
				if err != nil {
					log.Printf("error writing metric: %v", err)
				}
		}
	}()
}
```
Так ты добьешься двух вещей:

- избавишься от большого количества лишней работы
- перестанешь пересоздавать файловый дескриптор.

2024-12-27 12:39 UTC, frolmr commented on internal/server/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
убрал глобальное состояние, логгер теперь инжектится эксплицитно, оставил как мидлварь для chi, не знаю на сколько это ок

2024-12-27 12:39 UTC, frolmr commented on internal/agent/metrics/reporter.go
> +func (mc *MetricsCollection) ReportCounterMetrics(client *resty.Client) {
поправил

2024-12-27 12:41 UTC, frolmr commented on internal/server/storage/snapshot.go
> +func (ms *MemStorage) SaveToSnapshot(filePath string) {
поменял: 
- сделал абстракнтый Snapshooter который работает с дескриптторами ввода ввывода
- добавил фаловый Snapshooter который работает с фалами для снимков

2024-12-27 12:47 UTC, frolmr commented on internal/server/storage/snapshot.go
> +	for name, value := range ms.CounterMetrics {
это не сделал ((
в отдельной ветке попробовал bbolt, вроде как, даже завелось, но автотесты требуют файлов
что касается, дописывания в конец файла, я все равно не убедился, что это лучше:
- да мы постоянно открываем файловый дескриптор, но это как с пулером коннектов к БД, который нам выдает новый коннект по требованию (в то же время сам пулер держит коннекты, да)
- но ИМХО лучше раз в 5 минут открыть файл и закрыть, чем раз в 10 секунд писать в конец, а потом в холостую читать 100500 записей, рискуя держать открытым файл, который может переполнится без ротации или какой-то соседний процесс его прибьет

2024-12-27 14:09 UTC, zhark0vv commented on internal/server/storage/snapshot.go
> +	for name, value := range ms.CounterMetrics {
Спасибо, что попробовал, в любом случае!
Мои замечания - это не абсолют, их тоже можно челенджить.

2024-12-27 14:11 UTC, zhark0vv commented on internal/server/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Все ок, у меня нет возражений по поводу твоего решения.

2025-01-06 11:08 UTC, merged